import localFont from 'next/font/local'
import './globals.css'
import Navbar from '@/components/layout/Navbar'
import Sidebar from '@/components/custom/Sidebar/sidebar'
import { Toaster } from '@/components/ui/sonner'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar />
        <main className="flex pt-[60px]">
          <Sidebar />
          <div className="grow pl-[250px]">{children}</div>
          <Toaster />
        </main>
      </body>
    </html>
  )
}
